### ISSUE TITLE
Unauthorized contacts request causes invalid state

### ISSUE THREAD

**Issue by bpglaser** [TeamParrot/PersonalContactManager#18]
Steps to reproduce:

1. Successfully login as user
2. Request contacts from api
3. API returns 401 UNAUTHORIZED
4. React client enters invalid state

![image](https://user-images.githubusercontent.com/10121439/52053474-6c27a300-2527-11e9-8f55-cd0206439015.png)

Temporary fix:

1. Clear cookie on client
2. Refresh page
3. Re login

Expected behavior:

Any time the API endpoints return a 401, the react client should update to reflect the not logged-in state.

**Comment by bpglaser** [comment]
Update:

This bug occurs whenever the server returns a 401.

**Comment by Cyral** [comment]
Will fix soon
